### ISSUE TITLE
Can't compile on arch

### ISSUE THREAD

**Issue by nik9000** [alttpo/bsnes-as#1]
I was looking to compile this on arch and kept getting errors in the `discord` directory. Ultimately I was able to compile it by doing:
```
pushd discord
find -type f -exec sed -i s/std::uint/uint/g {} \;
find -type f -exec sed -i s/std::int/int/g {} \;
popd
```

I'm not really a C developer so I can't really debug any further. Do you intend for this to work? I love the idea of using the docker container to build the artifacts but I couldn't figure out how to get at what it built.

**Comment by nik9000** [comment]
> I couldn't figure out how to get at what it built.

If you could add instructions for getting the files out then I suppose you wouldn't need to support silly stuff like building on "my" distro.

**Comment by JamesDunne** [comment]
I left in a way to disable the discord integration in the Makefiles. Try `make discord=false`.

**Comment by JamesDunne** [comment]
> > I couldn't figure out how to get at what it built.
> 
> If you could add instructions for getting the files out then I suppose you wouldn't need to support silly stuff like building on "my" distro.

The build ends up in the `bsnes/out` directory. It took me a while to figure all this out too. I didn't set up the build system originally. It's a fork of the bsnes project.
